// Generated by CoffeeScript 1.7.1
(function() {
  var onDragEnd, onDragMoveRotateX, onDragMoveRotateY, onDragMoveRotateZ, prepareXRotationSlider, prepareYRotationSlider, prepareZRotationSlider, rotateView, xRotationVal, yRotationVal, zRotationVal;

  xRotationVal = 0;

  yRotationVal = 0;

  zRotationVal = 0;

  $(function() {
    prepareXRotationSlider();
    prepareYRotationSlider();
    prepareZRotationSlider();
    return $('.reset-all').on('click', function() {
      return $('.cool').removeAttr('style');
    });
  });

  onDragMoveRotateX = function(instance, event, pointer) {
    var $triggerKnob, sliderFill, sliderPercent;
    $triggerKnob = $(instance.element);
    sliderFill = instance.position.x / instance.containerSize.width;
    sliderFill = (sliderFill < 0 ? 0 : sliderFill);
    sliderPercent = Math.round(sliderFill * 100);
    xRotationVal = Math.round(sliderFill * 382);
    $triggerKnob.siblings(".slide-filled").css("width", sliderPercent + 1 + "%");
    $triggerKnob.children(".slide-value-modal").html(xRotationVal);
    $triggerKnob.children(".slide-value-modal").addClass("visible");
    rotateView();
  };

  onDragMoveRotateY = function(instance, event, pointer) {
    var $triggerKnob, sliderFill, sliderPercent;
    $triggerKnob = $(instance.element);
    sliderFill = instance.position.x / instance.containerSize.width;
    sliderFill = (sliderFill < 0 ? 0 : sliderFill);
    sliderPercent = Math.round(sliderFill * 100);
    yRotationVal = Math.round(sliderFill * 382);
    $triggerKnob.siblings(".slide-filled").css("width", sliderPercent + 1 + "%");
    $triggerKnob.children(".slide-value-modal").html(yRotationVal);
    $triggerKnob.children(".slide-value-modal").addClass("visible");
    rotateView();
  };

  onDragMoveRotateZ = function(instance, event, pointer) {
    var $triggerKnob, sliderFill, sliderPercent;
    $triggerKnob = $(instance.element);
    sliderFill = instance.position.x / instance.containerSize.width;
    sliderFill = (sliderFill < 0 ? 0 : sliderFill);
    sliderPercent = Math.round(sliderFill * 100);
    zRotationVal = Math.round(sliderFill * 382);
    $triggerKnob.siblings(".slide-filled").css("width", sliderPercent + 1 + "%");
    $triggerKnob.children(".slide-value-modal").html(zRotationVal);
    $triggerKnob.children(".slide-value-modal").addClass("visible");
    rotateView();
  };

  onDragEnd = function(instance, event, pointer) {
    $(instance.element).children(".slide-value-modal").removeClass("visible");
  };

  rotateView = function() {
    return $(".cool").css("-webkit-transform", 'rotateX(' + xRotationVal + 'deg) rotateY(' + yRotationVal + 'deg) rotateZ(' + zRotationVal + 'deg)');
  };

  prepareXRotationSlider = function() {
    var $containerRotateX, domElement, draggieRotateX;
    $containerRotateX = $('.slide-control-rotateX');
    $containerRotateX.children('.slide-knob').css('left', '50%');
    $containerRotateX.children('.slide-filled').css('width', '51%');
    domElement = $containerRotateX.children('.draggable')[0];
    draggieRotateX = new Draggabilly(domElement, {
      axis: "x",
      containment: $containerRotateX
    });
    draggieRotateX.on('dragMove', onDragMoveRotateX);
    return draggieRotateX.on('dragEnd', onDragEnd);
  };

  prepareYRotationSlider = function() {
    var $containerRotateY, domElement, draggieRotateY;
    $containerRotateY = $('.slide-control-rotateY');
    $containerRotateY.children('.slide-knob').css('left', '50%');
    $containerRotateY.children('.slide-filled').css('width', '51%');
    domElement = $containerRotateY.children('.draggable')[0];
    draggieRotateY = new Draggabilly(domElement, {
      axis: "x",
      containment: $containerRotateY
    });
    draggieRotateY.on('dragMove', onDragMoveRotateY);
    return draggieRotateY.on('dragEnd', onDragEnd);
  };

  prepareZRotationSlider = function() {
    var $containerRotate, domElement, draggieRotateZ;
    $containerRotate = $('.slide-control-rotateZ');
    $containerRotate.children('.slide-knob').css('left', '50%');
    $containerRotate.children('.slide-filled').css('width', '51%');
    domElement = $containerRotate.children('.draggable')[0];
    draggieRotateZ = new Draggabilly(domElement, {
      axis: "x",
      containment: $containerRotate
    });
    draggieRotateZ.on('dragMove', onDragMoveRotateZ);
    return draggieRotateZ.on('dragEnd', onDragEnd);
  };

}).call(this);
